### PR TITLE
Transform origin fixes

### LINKED ISSUE #1460: Transforms don't apply transformOrigin correctly
transformOrigin is implemented only for rotate. But unapply isn't implemented correctly. Also transformOrigin should work for skew and matrix too.

I am working on a fix. Will update with a PR.

image

### PR DESCRIPTION
**Pull request by KurtGokhan**
Fixes #1460 

Didn't apply the fix to `applyToPoint`, as I don't know what that does.

### CODE REVIEW

**Comment by gabelerner** [comment]
@KurtGokhan i merged some PRs so this needs to be rebased. `applyToPoint` isn't used, I'll remove it at some point

**Comment by KurtGokhan** [comment]
@gabelerner  fixed conflicts. Please check again.

**Comment by gabelerner** [comment]
@KurtGokhan merged the other one, reran your tests here, getting a 7% difference on your new snapshots, might want to regenerate them?

**Comment by KurtGokhan** [comment]
Looks like the test added by #1458 was failing. Coincidentally, that test included a non-root SVG element whose default transform-origin should be 0 (except if it is direct child of a `foreignObject`). Fixed now.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform-origin#usage_notes

**Comment by gabelerner** [comment]
looks fine to me, i'll give dangreen a day or two to look at it if he has time. if not i'll approve/merge. maybe we do a release right after.

**Comment by KurtGokhan** [comment]
@dangreen @gabelerner  any luck?

**Review by gabelerner — APPROVED** [review]

**Comment by gabelerner** [comment]
@KurtGokhan i merged, now to figure out the release process ... should be sometime by Sunday unless Dan beats me to it.  Are you interested in further contributions to canvg?  You seem to have a hang for the codebase and I can just make you a contributor where you'll be able to run tests/deploy/etc.

**Comment by KurtGokhan** [comment]
@gabelerner Yes, I am interested. I may pick bugs and issues occasionally.

**Comment by gabelerner** [comment]
@KurtGokhan i may not get to a deploy this weekend due to some personal/work stuff that came up, but i'll push one out as soon as i can, it's on my todo list

**Comment by KurtGokhan** [comment]
Also fixes #1435

@gabelerner  It has been a while. Is there a plan to create a new release soon?

**Comment by gabelerner** [comment]
https://github.com/canvg/canvg/pull/1471 i put a release up here, if @dangreen doesn't accept soon I'll add you as a contributor and you can approve

**Pull request merged**
