### PR TITLE
bump rgbcolor version

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@gabelerner can you merge this?

**Comment by MarkMaldaba** [comment]
Doesn't this also require that rgbcolor.js is also updated to match, and the various builds recreated?  Or does that happen via some other mechanism?

**Comment by graingert** [comment]
@MarkMaldaba oh that file is unused now

**Comment by MarkMaldaba** [comment]
How does that work with the release builds?  Does it get pulled in automatically when creating the zip file?  Or is it just not needed at all?

Shouldn't it be removed from the repo if it's unused?

**Pull request merged**
