### PR TITLE
Release/3.0.9

### PR DESCRIPTION
**Pull request by dangreen**
### Fixed
- [#1480](https://github.com/canvg/canvg/issues/1480)
- [#1484](https://github.com/canvg/canvg/issues/1484)

### CODE REVIEW

**Review by gabelerner — APPROVED** [review]
LGTM

**Comment by dangreen** [comment]
@gabelerner Can you publish this? Currently I have some issues with network, I can't publish.

**Comment by gabelerner** [comment]
@dangreen sure, is it the same clean publish command I ran last time?

**Comment by dangreen** [comment]
@gabelerner yes

**Comment by gabelerner** [comment]
@dangreen ok published! thanks for fixing

**Pull request merged**
