### PR TITLE
Upgrade canvg with DPI resolution

### PR DESCRIPTION
**Pull request by individuell-design**
scales canvas to match dpi resolution (default is 72 dpi, set to 300 for print resolution)
- search "dpi" for changes in lines.
- upgrades were made based on https://cdnjs.cloudflare.com/ajax/libs/canvg/1.5/canvg.js

### CODE REVIEW

**Comment by gabelerner** [comment]
something like http://jsfiddle.net/paultrotter50/L407d2q3/9/ should work on your higher DPI devices and therefore you can just use the scaling options in canvg to achieve a similar result. please reopen if i'm wrong.

**Comment by individuell-design** [comment]
Hi, 
Sorry I was busy last days to answer back.
I had problems to use scale option so I have modified your script for my needs and I just wanted to share it with you. If you don’t want this function then its up to you. Sorry I’m noob at github.com so I don’t know all functions and how to use it and share code changes yet, but you can check out the code changes (link below) and implement it. There are only 6 lines you need to upgrade (5min work) to add DPI function.

open this code (v1.5) and search for svg.dpi
https://github.com/individuell-design/canvg/blob/86e62016cc3a850ffdb484658e56543b064284f6/src/canvg.js

default is 72dpi, so to use DPI change add dpi option (opts) in canvg call. 
example:
canvg(svg,{dpi:300,renderCallback:callback})

with kind regards from Germany
Dieter

Gesendet von Mail für Windows 10

Von: Gabe Lerner
Gesendet: Samstag, 3. November 2018 16:55
An: canvg/canvg
Cc: individuell-design; Mention
Betreff: Re: [canvg/canvg] Upgrade canvg with DPI resolution (#636)

something like http://jsfiddle.net/paultrotter50/L407d2q3/9/ should work on your higher DPI devices and therefore you can just use the scaling options in canvg to achieve a similar result. please reopen if i'm wrong.

**Comment by gabelerner** [comment]
@individuell-design i read the code and it still seems like you can just use the `scaleWidth` and `scaleHeight` options without modifying the script itself.  let me know if you have an example and i can show you how.

**Comment by individuell-design** [comment]
Hi,
I’m professional in JavaScript, so I tried with scale year ago. Maybe it was buggy then, or it did not worked properly with all browsers (cannot remember and I did not tried with current versions). So that’s why I changed the script for me end imbedded DPI scale. Again this is not much of work to add this new option, and for Designers its easier to work with DPI than scale (Math). If I want output Screen I use 72dpi for Mobile I work with 96dpi and for print 300dpi – its much easier.

Gesendet von Mail für Windows 10

Von: Gabe Lerner
Gesendet: Sonntag, 4. November 2018 01:18
An: canvg/canvg
Cc: individuell-design; Mention
Betreff: Re: [canvg/canvg] Upgrade canvg with DPI resolution (#636)

@individuell-design i read the code and it still seems like you can just use the scaleWidth and scaleHeight options without modifying the script itself. let me know if you have an example and i can show you how.

**Comment by individuell-design** [comment]
Hi,
I know this, its simple Math. But it did not worked for me then. It was cut out or blurred/pixelated then when you output big Image.
Also you say render SVG 100x100 at 416x416, but If I live edit SVG 600x800 I cannot change the size. Its logical to not touch the size of the svg but change the rendering resolution.


Gesendet von Mail für Windows 10

Von: Gabe Lerner
Gesendet: Sonntag, 4. November 2018 17:27
An: canvg/canvg
Cc: individuell-design; Mention
Betreff: Re: [canvg/canvg] Upgrade canvg with DPI resolution (#636)

All you're doing though is dividing by an assumed 72ppi to get a ratio and then passing that into the scale. I don't want the code making more assumptions than it already does and having multiple options that essentially do the same thing. All you have to do is take your desired dpi 300/72 = 4.16 and then if your svg is 100x100, render it at 416x416 with scaleHeight: 100, scaleWidth: 100 and you'll get the same results.

**Pull request closed without merging**
