### PR TITLE
Fix/1196

### PR DESCRIPTION
**Pull request by dangreen**
https://github.com/canvg/canvg/issues/1196

- [x] PathParser refactoring
- [x] `PathElement` and `TextPathElement` mods
- [x] Select common code from `PathElement` and `TextPathElement`

### CODE REVIEW

**Comment by dangreen** [comment]
@gabelerner Can you please add "hacktoberfest" topic to repo ?

**Comment by gabelerner** [comment]
@dangreen done

**Comment by dangreen** [comment]
@gabelerner review 🙏

**Review by gabelerner — APPROVED** [review]
looks good from here. seems like you replaced regex with a 3rd party (svg pathdata), then pulled path element methods out to static so you could reuse them in the text path element.

**Comment by dangreen** [comment]
@gabelerner Yes. Previous regexp parser worked incorrect. For example: `A3.5 3.5 0 113-.5 3.5 3.5 0 016.5 3` should parsed as `A 3.5 3.5 0 1 1 3 -.5 A 3.5 3.5 0 0 1 6.5 3`, but `016.5` was parsed as `0 16.5` instead of `0 1 6.5`.

**Pull request merged**
