### PR TITLE
Separate builds for node and browser

### PR DESCRIPTION
**Pull request by amenadiel**
In this PR the following changes are implemented:

 - there is a single source file `canvg.src.js` (any modifications must be done in this file from now on)
   - This file is used by [Rollup](https://rollupjs.org) to generate `canvg.js` and `canvg.node.js`.
   - I suggest adding a `CONTRIBUTING` section to README.md or a PR template to remind the contributors not to modify `canvg.js` nor `canvg.node.js`. They should modify only `canvg.src.js` and then build.

 - when running `npm run build` it will generate `canvg.js` and `canvg.node.js`
   - `canvg.js` is meant for usage in the browser and doesn't use `jsdom` nor `xmldom`
   - `canvg.node.js` is meant for usage in node, and therefore it uses `jsdom` and `xmldom` to simulate the window behavior
   - Builds can be generated separately by running `npm run build:browser` and `npm run build:node`

- Tests are ran using [AVA](https://www.npmjs.com/package/ava) and reported to the console using [tap-diff](https://www.npmjs.com/package/tap-diff). The command is still `npm run test`.
  - Browser side tests are ran by instantiating a local webserver on port `3123` (can be changed with ENV variables) then using [puppeteer](https://github.com/GoogleChrome/puppeteer) to simulate user interaction with a headless browser. Actual generated images are saved to `test/actual_browser`
  - Node tests are ran with AVA in the same way they are ran actually, but actual results are saved to `test/actual_node`.
  - browser and node tests can be run separately using  `npm run test:node` and `npm run test:browser`

 - Both browser and node tests consider the test passed if the generated images are similar (given a certain threshold) to the expected image. Similarity is determined using [blink-diff](https://www.npmjs.com/package/blink-diff)
   - The difference between images, when their difference is above the threshold, are stored in `test/diff_node` and `test/diff_browser` for further inspection.

  - given that now we're using a testing framework, the test tasks will exit with non-zero status if any test fails. (prior to this PR, it didn't matter if tests failed). This is the intended behavior for tests tasks if you want to automate them using (for exaple) Travis.

 - files to test are listed in  `test/_svgs.js` as a object with structure `{file: description}` to provide more info about the test we are running. Prior to this, the files to test where obtained from the `svgs` folder. 

- Users can test the examples by running `npm start` and navigating to `http://localhost:3123/examples/index.htm`. I added this instruction to README.md

- I added an alternative example index at `examples/index.html` which also displays
  - The image from `test/expected` as dataURI
  - The image from `test/expected` as blob
  - The image from canvg as dataURI (using `canvas.toDataURL`)
  - The image from canvg as blob (using `canvas.toBlob`)

### CODE REVIEW

**Comment by fuzhenn** [comment]
Bravo works!

I notice `canvg.js` (browser version) is set to package.json's main field, which is also the entry for node applications.

You may consider to move `canvas.js` to [browser](https://docs.npmjs.com/files/package.json#browser)  field and set `canvg.node.js` to main field, but this will need some extra config to tell webpack/rollup to consume `browser` instead of `main` when packing your apps.

**Comment by amenadiel** [comment]
Hmmm you're right. I was used to put `main`, `module` and `jsnext:main`. According to [npm documentation](https://docs.npmjs.com/files/package.json#browser):

> If your module is meant to be used client-side the browser field should be used instead of the main field. This is helpful to hint users that it might rely on primitives that aren't available in Node.js modules. (e.g. window)

So, @fuzhenn if I understand correctly, the `package.json` should contain:

```
{
 ...
 "main": "canvg.node.js",
 "browser": "canvg.js",
 ...
}
```

So bundlers will use the `main` entrypoint whereas (for example) jspm would use the `browser` entry?

**Comment by gabelerner** [comment]
i'll take a look at this soon, the direction looks good here.  some early thoughts:

maybe it's worth putting the built files into `/dist` or `/build` ... then there you can have a `/node` folder and a `/web` folder each having a `canvg.js` (with web also having `canvg.min.js` perhaps).  the main file can also just stay as `canvg.js` then.  this should reduce ambiguity as to what is happening even though we will still update the README.

we can also then .gitignore the `/dist` or `/build` folder in the main trunk of master.  then we can make a release branch that doesn't have it gitignored and tag there every time we want to publish a new release to github.  this way most users will just see the source when looking at github master.

thoughts on this?

**Comment by amenadiel** [comment]
I agree we should move the builds to a `dist` folder. Wether to ignore them or not, it's not my call. But this way the source file could still be named just `canvg.js`.

**However...**, the source file has some code that Rollup replaces for the build to make any sense (__IS_NODE__. __DOM_PARSER__, etc) . If people are mislead to download and copy `canvg.js` to their project the will just get a file full of placeholders.

Perhaps we should also create an `src` folder that would be ignored on the `package.json` or the `.npmignore` file.

**Comment by gabelerner** [comment]
@amenadiel i like your thinking

let's do this if you're ok w/ it:
1) move builds to
```
/dist
  /node
    canvg.js
    canvg.min.js
  /browser
    canvg.js
    canvg.min.js
```
2) move src to
```
/src
  canvg.js
```
3) remove `/src` and `/dist/browser` from npm whichever way you think is best
3) document in `README` that to install on browser point script tag at CDN or use `/dist/browser` files locally and to install on node, use `yarn add canvg` or whatever

**Comment by amenadiel** [comment]
Okay, so I made the following changes:

- builds go into `/dist/node` and `/dist/browser` (with their respective minifications)
- source was moved to `/src/canvg.js` 
- I added an option to instance the `DOMParser` that can silence `xmldom` warning during tests. Otherwise, everything behaves as usual.
- I wasn't satisfied with the way I dealt with the source file. Having all those placeholders:

```js
   nodeEnv = __NODE_ENV__,
   jsdom = __JSDOM__,
   windowEnv = __WINDOWENV__;
   windowEnv.DOMParser = __DOMPARSER__;
```

meant people had to build to actually test their changes. I used a more clever approach to have `nodeEnv` defined according to `(module.exports !== undefined && typeof window === 'undefined')` in the sourcefile, whereas the build replaces the definition with `true` or `false`, which results in a build that only includes the needed blocks (shaves off 12Kb from both builds)

- Thanks to the above, the tests can be ran against the sourcefile instead of the node build. It seems more practical

- I added a banner to the build that is the same you had but it updates the version number according to `package.json` so now it says something like

```js
/*
 * canvg.js - Javascript SVG parser and renderer on Canvas
 * version 1.5.1
 * MIT Licensed
 * Gabe Lerner (gabelerner@gmail.com)
 * https://github.com/canvg/canvg
 *
 */
```

- I ignored the `src` folder using `.npmignore`. However, I don't agree on ignoring `dist/browser`. See, people including this library with `jspm` or `webpack` will install from npm, therefore they should get the browser build as well. 

- I'm not sure about needed changes in README.md. With the new structure the following:

```html
<script type="text/javascript" src="http://canvg.github.io/canvg/canvg.js"></script> 
```

Will no longer apply **but**  if I understand correctly, `http://canvg.github.io/canvg` obeys to the current layout of the `gh-pages` branch, which doesn't seem to have been updated in a while. If I changed the README to point people to

```html
<script type="text/javascript" src="http://canvg.github.io/canvg/dist/browser/canvg.js"></script> 
```
It wouldn't work because the `gh-pages` branch doesn't have that path yet. Perhaps we should consider using **jsdelivr** for that. For example, I can display my branch (which I temporarily tagged as v1.5.1) at

https://cdn.jsdelivr.net/gh/huasofoundries/canvg/dist/browser/canvg.js

That url will always deliver the latest version.

You could do the same using:

https://cdn.jsdelivr.net/npm/canvg/canvg.js

or, eventually

https://cdn.jsdelivr.net/npm/canvg/dist/browser/canvg.js

Once this PR is merged and published to NPM. Otherwise, the second URL will not resolve, and the README.md will be misleading. I believe that you must perform that last modification once you merge, publish and update `gh-pages`.


> we shouldn't require EVERY PR to run the build and will just do it w/ release PRs I guess

I meant quite the opposite. That PRs should only alter `/src/canvg.js` and avoid building. Since now the node test is ran against the source file, they shouldn't build anymore. That task should depend on you or your mantainers, because the builds shouldn't change unless there is a version bump.

**Finally:**

Everytime a new version is released, the `package.json` version field must be bumped (and obey semantic versioning `<major>.<minor>.<hotfix>`. In the current state, even the `v1.5` release has a `package.json` that declares the version as `1.0.0`, which means that NPM will check that field and list the package with said version. People will get confused as to why they aren't getting `v.1.5`. In this PR I bumped the version to `v.1.5.1` in `package.json`, but I believe you need to push a tag that matches the version before publishing to npmjs.org.

**Comment by gabelerner** [comment]
@Pauan thoughts?

**Comment by gabelerner** [comment]
@amenadiel great work, i backmerged some stuff from master and ran through all the npm scripts. i'm going to do a lot of housekeeping soon including:
- 2 spaces instead of 4
- unix line endings
- prettier formatting of most files
- updating README a bit
- add CI

then i'll probably republish and start tackling issues again

also i don't hate how much coverage we're getting just from the example svgs
screen shot 2018-08-07 at 6 46 47 pm

**Comment by amenadiel** [comment]
@gabelerner @fuzhenn thanks for the feedback and for merging my humble contribution. This made my day.

For a moment I thought I forgot to remove `nyc` from  `package.json`, but I guess you have it installed locally.

I believe, tho is just my opinion, that we should carefully calibrate the tolerance for `blink-diff`. The issue #593 you tackled today was not appearing as broken because, all things considered, the output was pretty similar in the eyes of said tool.

Perhaps the test list pulled from `test/_svgs.js` should have more granularity and group tests by some criteria: the ones that rely on fonts, the ones that rely on gradients, and so on. That way instead of testing every file in just one script `test/node.test.js` there could be a collection like  `test/node.font.test.js`, `test/node.gradient.test.js`, `test/node.path.test.js` and so on, and so on.

In each of them the comparison criteria might be passed a different tolerance parameter. 

Also, since you already started working con CI, broken tests should be under a different group `test/node.broken.test.js` that could be skipped in the runner and tackle each one of them one at a time.

Keeping the ones that do pass will allow to have travis passing the tests, but more important, will allow tu use CI as a regression test. You know you can fix issues and move them to "whitelisted" groups, but if a commit breaks a test that was formerly passing, then it is really valuable that Travis CI chokes and gags.

Otherwise, since we know there are 15 tests that fail, Travis is telling us something we already know.

**Comment by gabelerner** [comment]
@amenadiel i love that idea around testing and splitting tests to have different tolerances and maintaining a whitelist of tests that are allowed to fail for now. i'm going to be focusing on a few other things.  if you have some time to tackle this part, that would be much appreciated! travis is ready to go in master :)

**Comment by mistic100** [comment]
IMHO this should NOT have been published as a "patch" version. It may be retrocompatible but it's very risky anyway.

**Comment by amenadiel** [comment]
I call dibs on separating the tests. 

Also, if you're okay with that, I'd use that same grouping definition to populate the select elements in the example, so adding a new issue (ilke 593) would follow the procedure:

1. copying the offending SVG to `/svg`
2. copying the expected PNG to `/test/expected`
3. adding the issue and its description to `/test/_svgs.js` either under `issues.broken` or `issues.passing`.

So any PR in the form: "Solves issue #XYZ" should go through these steps (if the issue isn't already in there) and prove (using travis) that it is now solved.

**Comment by gabelerner** [comment]
@mistic100 i can unpublish and go minor or major but here was my rationale for doing it:
- test suite has similar # of tests passing at 85% coverage
- i manually diffed the resulting node build against the existing file
- technically the only difference was a couple bug fixes

let me know your thoughts in support of the other direction please

@amenadiel i'm good with that process

**Comment by mistic100** [comment]
Oh no, do not unpublish the version, that's the worst thing to do. It was just a general remark for future releases.

BTW I confirm this version works perfectly in my Webpack 3 build process.

**Pull request merged**
