### PR TITLE
Removed unneeded ternary

### PR DESCRIPTION
**Pull request by tm93112**

### CODE REVIEW

**Comment by gabelerner** [comment]
for us to merge, please add tests.

you can follow a sample PR such as https://github.com/canvg/canvg/pull/1067/commits/5674166af89d5d173892be73ada0b78b789cbaa8 to add an example svg file that previously wasn't working then was working

the test will then produce an artifact that you can download with the "expected" results
https://travis-ci.com/github/canvg/canvg/builds/166645958
image


you can then make another commit to turn off the test w/ the expected results https://github.com/canvg/canvg/pull/1067/commits/010d922f34ac7221219f6235969f7cac86ba5d74 and the build should pass

**Comment by gabelerner** [comment]
@dangreen 241 became more accurate w/ this PR too (the red matches chrome more than the pink)

**Comment by gabelerner** [comment]
I don't know why branch build isn't running but pull request build passed. I think it's good to merge. Thoughts @dangreen?

**Comment by dangreen** [comment]
@gabelerner 

> I don't know why branch build isn't running 

Travis should be enabled in tm93112's fork.

Bu we can trust pull request's travis build )

**Pull request merged**
