### PR TITLE
allow dependencies to be loaded by webpack

### PR DESCRIPTION
**Pull request by austinhallock**
unsure of effect on requirejs (untested, not familiar with requirejs)

### CODE REVIEW

**Comment by jdelight** [comment]
Can also be solved by adding the following to your webpack config - basically does what your PR does :)
```js
    resolve: {
        alias: {
            'rgbcolor': './rgbcolor',
            'stackblur': './stackblur'
        },
    },
```

**Comment by gabelerner** [comment]
is there a test for require here? otherwise people are just fighting in PRs around the right state of all these config files

**Comment by alettieri** [comment]
+1

**Comment by csvan** [comment]
+1

**Comment by gabelerner** [comment]
should be fixed by https://github.com/canvg/canvg/pull/591

**Pull request closed without merging**
