### PR TITLE
Fix/747: check filter size before draw

### PR DESCRIPTION
**Pull request by dangreen**
https://github.com/canvg/canvg/issues/747

### CODE REVIEW

**Comment by gabelerner** [comment]
the generated test images don't seem to have anything - the original issue image has some colored lines on the left side.

**Comment by dangreen** [comment]
@gabelerner if remove `<filter>` then there no lines

**Comment by gabelerner** [comment]
i'm confused here - the original svg https://jsfiddle.net/xck8og02/ has a line that renders in chrome. our checked in versions have no line, but imo we should try to match chrome unless we feel chrome is wrong?

**Comment by dangreen** [comment]
@gabelerner canvg currently doesn't support `<fe*` elements, svg without them: https://jsfiddle.net/b8rzphqg/

snapshots it is what produced by canvg, not by chrome

**Comment by gabelerner** [comment]
ok fair enough! I forgot we don't support them although I thought we supported some so there could have been a better test case. Approving!

**Pull request merged**
