### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by brettz9**
- Linting (ESLint): Add config with recommended rules (overriding `no-useless-escape`, `no-redeclare`, and for tests, `no-console`), npm script
- Refactoring (ESLint): Comment out non-problematic unused variables to avoid lint flagging, avoid unclear variable redeclaration, remove unreachable code (break after return), avoid tabs mixed into spaces, avoid global `closeMe` variable and undeclared variable in `_server.js`
- Refactoring (HTML linting): Avoid spec and implementation unnecessary `type="text/javascript"` and type="text/css"; use HTML5 DOCTYPE and meta charset (and before title)
- Refactoring (package.json linting): Add recommended fields: `bugs`, `engines`, and `contributors` (also used on npmjs.com)

While applying eslint:recommended rules, I tried to stick to your existing rules and avoid refactoring suggestions for now except to fix likely unintended issues (e.g., mixed tabs and spaces). While I honored your use of some redundant regex escapes (`no-useless-escape` in ESLint), I personally prefer to enforce that rule if you were open to it. I disabled `no-console` in the testing directory for obvious and I think reasonable reasons. The one pseudo-refactoring I did was to comment out albeit non-problematic unused variables so as to allow genuinely problematic unused variables to be detectable in the future. The reason I suppressed the `no-redeclare` rule in `canvg.js` is because I'd like to make a PR adding Babel support and then use `let` and `const` within the used block scope, rather than doing work now to move `var` to the top of the scope only to have to undo it later.

One can get some more fine-tuned control (including finding some potentially issues not flagged by eslint:recommended) with something like eslint-config-standard, but I thought I'd keep it simple for starters.

### CODE REVIEW

**Comment by brettz9** [comment]
One oddity is that although running `npm test` showed all the tests passing, it ended as though there were an error.

I plan to rebase shortly as I see you have new commits...

**Comment by brettz9** [comment]
Ok, rebased... (though I can rebase again if you need to first merge older PRs, as I imagine my PRs will only keep adding to the amount of refactoring that would have to be done on them).

**Comment by brettz9** [comment]
Oh, and you might want to look at that `closeMe` variable to see about out removing what is now commented out or indicating that it is a global that should be there (hopefully indicating why we need it in source)...

**Comment by brettz9** [comment]
Cool, thanks!

Re: the test server, FWIW, I have found helpful [`node-static`](https://www.npmjs.com/package/node-static) (including its [CLI](https://github.com/cloudhead/node-static#command-line-interface)) (and if you want the main demo file page to auto-open, [`opn-cli`](https://www.npmjs.com/package/opn-cli)), for effective succinct npm scripts...

Re: yarn, as long as it continues to install with npm, that's cool with me... I guess you'll just take out `package-lock.json`, add `yarn.lock`, and reference `yarn` in the npm scripts?

Re: Canvas, cool...

**Comment by gabelerner** [comment]
@brettz9 i pushed out v1.5.4 on some prior fixes just before i merge this to master. can you backmerge again and then i'll merge. i tried but it seems like i don't have permissions to push to your remote branch.

**Comment by brettz9** [comment]
Rebasing done and looks like Travis tests are passing...

**Comment by gabelerner** [comment]
@brettz9 gave you write access to you can just open PRs in this repo

**Comment by brettz9** [comment]
Cool, so I should push my branches here then?

**Comment by brettz9** [comment]
Also, what's the deal with canvas 2.0? If it's related to it not being easy or possible to Rollup, how about just leaving a `require`?

**Pull request merged**
