### PR TITLE
3.0.4

### PR DESCRIPTION
**Pull request by gabelerner**

### CODE REVIEW

**Comment by dangreen** [comment]
@gabelerner why 3.0.4? 3.0.3 is not published
https://www.npmjs.com/package/canvg

**Comment by gabelerner** [comment]
i unpublished that one and it won't let me republish

**Comment by dangreen** [comment]
@gabelerner can you give publish access rights to me?

**Comment by gabelerner** [comment]
i'll look into access rights later this week about to go to bed - what username/email are you on npm? you can also send it to me at gabelerner at gmail.com

**Comment by dangreen** [comment]
https://www.npmjs.com/~dangreen


вт, 7 янв. 2020 г. в 14:07, Gabe Lerner <notifications@github.com>:

**Pull request merged**
