### PR TITLE
Fixed undef variable

### PR DESCRIPTION
**Pull request by diegotremper**

### CODE REVIEW

**Comment by marcospont** [comment]
Those undefined variables are preventing us from running canvg in strict mode.

**Comment by mvmeirose** [comment]
Thanks Diego!

**Comment by jazzzz** [comment]
Is there something blocking the merge of this MR?
This issue creates a global `i` and prevents using canvg in strict mode.

**Comment by gabelerner** [comment]
nothing blocking except for me having time to look through PRs

**Pull request merged**
