### PR TITLE
native handling of <svg> elements

### PR DESCRIPTION
**Pull request by sweetleon**
allows us to get the element's styles from the browser

### CODE REVIEW

**Comment by gabelerner** [comment]
there are a lot of good ideas here, i'll break them out into separate PRs.  the native styles might be its own optional js file people can include if they want and the rest are bugfixes. thanks!

**Comment by sweetleon** [comment]
I like the idea of having native styles as an optional add-in, tho I don't
quite understand when someone wouldn't want them if they're available.

On Sunday, February 15, 2015, Gabe Lerner <notifications@github.com> wrote:

> there are a lot of good ideas here, i'll break them out into separate PRs.
> the native styles might be its own optional js file people can include if
> they want and the rest are bugfixes. thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gabelerner/canvg/pull/327#issuecomment-74464019>.
>


-- 
--
Snet form a tiny keybord

**Comment by gabelerner** [comment]
depends on performance hit ... might just merge and see if anybody cares, looking at it now

**Comment by gabelerner** [comment]
closing because most of this has been handled w/ the specificity code

**Pull request closed without merging**
