### PR TITLE
Cors for cross origin problem

### PR DESCRIPTION
**Pull request by ghfkui**
Added timestamp in order to resolve the problem caused by cache.

### CODE REVIEW

**Comment by gabelerner** [comment]
what is the issue you are trying to resolve?

in most cases, we want to use the browser cache instead of fetching the image every time. that's why it exists and any user can clear it locally or just hard reload if they want to get a newer image.

**Comment by ghfkui** [comment]
Hi gabelerner,
it is related to cors(not same origin). The case is:
The image in svg used cloud resource in third party(not same origin) which can set 'allow origin'.
When used canvg to create thumb it still log "No 'Access-Control-Allow-Origin' header is present on the requested resource".

**Comment by gabelerner** [comment]
we already have https://github.com/canvg/canvg/blob/master/src/canvg.js#L3351

per https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image and https://medium.com/@albertogasparin/manipulating-cross-origin-images-with-html-canvas-1e3e8780964c

have you tried that flag? clearing browser cache doesn't magically solve cors issues.

**Comment by ghfkui** [comment]
Yes, I used that flag. But the error is still existed.

**Comment by gabelerner** [comment]
does the hosting server of the images allow CORS and is sending the appropriate headers? that's a prerequisite here. please configure the server to do so and it'll start working.

**Comment by ghfkui** [comment]
The server allow CORS. I uploaded a image as following:
image
When i set 'Disable cache' in developer tools in chrome or added timestamp as I was committed. It works fine.

**Comment by gabelerner** [comment]
and what if you just clear cache or use incognito? you must have cached something bad before cors was working and by disabling/clearing cache it's reading the new image w/ proper cors. is that correct?

**Comment by ghfkui** [comment]
Before using canvg, it would load image(it would be cached) to display firstly.

**Comment by ghfkui** [comment]
Added the timestamp to resolve the https://stackoverflow.com/questions/12648809/cors-policy-on-cached-image. Does it have property to resolve the issue in canvg?

**Comment by gabelerner** [comment]
the stackoverflow answer @ https://stackoverflow.com/a/51556805/146156 says that this could be fixed on the server side by ignoring origin or you can send origin in the first http request (when you load the image outside canvg).

essentially, any js library that makes an ajax call would have to do this (always add a timestamp) but i don't see this as a shortcoming in the library. this may be a shortcoming in chrome (too much security) but there are ways around it beyond changing every library to add a timestamp.

**Comment by ghfkui** [comment]
Ok. Gabelerner. thanks for your help.

**Pull request closed without merging**
